#############################################################################
# Makefile for building: execs/gpx-tests
# Generated by qmake (2.01a) (Qt 4.8.7) on: Fri Apr 5 14:59:48 2019
# Project:  GPX-Tests.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile GPX-Tests.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -Iheaders
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1
LIBS          = $(SUBLIBS)   -lboost_unit_test_framework 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/earth.cpp \
		src/gpx-tests.cpp \
		src/geometry.cpp \
		src/logs.cpp \
		src/position.cpp \
		src/route.cpp \
		src/track.cpp \
		src/xmlparser.cpp \
		src/xmlgenerator.cpp \
		src/gridworld.cpp \
		src/gridworld_route.cpp \
		src/gridworld_track.cpp \
		src/gpx-tests/name.cpp \
		src/gpx-tests/numpositions.cpp \
		src/gpx-tests/maxElevationN0774756.cpp \
		src/gpx-tests/accessOperator.cpp \
		src/gpx-tests/accessOperatorLogGenerator.cpp \
		src/gpx-tests/maxLongitudeN0743797.cpp \
		src/gpx-tests/steepestGradient.cpp \
		src/gpx-tests/steepestGradientN0742908.cpp \
		src/gpx-tests/steepestGradient-N0826291.cpp \
		src/gpx-tests/findNameOf.cpp \
		src/gpx-tests/findPositionN0724629.cpp \
		src/gpx-tests/findpositionn0734208.cpp \
		src/gpx-tests/maxSpeedN0737110.cpp \
		src/gpx-tests/maxlatitude.cpp \
		src/gpx-tests/maxSpeedN0733894.cpp \
		src/gpx-tests/N0774446-TotalHeightGain.cpp \
		src/gpx-tests/maxGradient-n0756303.cpp \
		src/gpx-tests/maxspeedn0736188.cpp \
		src/gpx-tests/totalLengthTest_n0755314.cpp \
		src/gpx-tests/netLength-N0704050.cpp \
		src/gpx-tests/restingTimeN0736563.cpp \
		src/gpx-tests/netHeightGain-N0679817.cpp \
		src/gpx-tests/netHeightGain-N0675532.cpp \
		src/gpx-tests/maxGradient-N0740369.cpp \
		src/gpx-tests/MaxElevation-N0749370.cpp \
		src/gpx-tests/minLongitude.cpp \
		src/gpx-tests/minlatitude-n0743587.cpp \
		src/gpx-tests/netLength-N0745509.cpp \
		src/gpx-tests/maxLongitude.cpp \
		src/gpx-tests/timesVisited-n0763258.cpp \
		src/gpx-tests/maxLongitudeN0732961.cpp \
		src/gpx-tests/netHeightGain-N0701387.cpp \
		src/gpx-tests/totalHeightGainN0724106.cpp \
		src/gpx-tests/netLength-N0731739.cpp \
		src/gpx-tests/minLongitudeN0735026.cpp \
		src/gpx-tests/findnameofn0665742.cpp \
		src/gpx-tests/maxlatitude_N0745180.cpp \
		src/gpx-tests/totalTime_N0751567.cpp 
OBJECTS       = earth.o \
		gpx-tests.o \
		geometry.o \
		logs.o \
		position.o \
		route.o \
		track.o \
		xmlparser.o \
		xmlgenerator.o \
		gridworld.o \
		gridworld_route.o \
		gridworld_track.o \
		name.o \
		numpositions.o \
		maxElevationN0774756.o \
		accessOperator.o \
		accessOperatorLogGenerator.o \
		maxLongitudeN0743797.o \
		steepestGradient.o \
		steepestGradientN0742908.o \
		steepestGradient-N0826291.o \
		findNameOf.o \
		findPositionN0724629.o \
		findpositionn0734208.o \
		maxSpeedN0737110.o \
		maxlatitude.o \
		maxSpeedN0733894.o \
		N0774446-TotalHeightGain.o \
		maxGradient-n0756303.o \
		maxspeedn0736188.o \
		totalLengthTest_n0755314.o \
		netLength-N0704050.o \
		restingTimeN0736563.o \
		netHeightGain-N0679817.o \
		netHeightGain-N0675532.o \
		maxGradient-N0740369.o \
		MaxElevation-N0749370.o \
		minLongitude.o \
		minlatitude-n0743587.o \
		netLength-N0745509.o \
		maxLongitude.o \
		timesVisited-n0763258.o \
		maxLongitudeN0732961.o \
		netHeightGain-N0701387.o \
		totalHeightGainN0724106.o \
		netLength-N0731739.o \
		minLongitudeN0735026.o \
		findnameofn0665742.o \
		maxlatitude_N0745180.o \
		totalTime_N0751567.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		GPX-Tests.pro
QMAKE_TARGET  = gpx-tests
DESTDIR       = execs/
TARGET        = execs/gpx-tests

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) execs/ || $(MKDIR) execs/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPX-Tests.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile GPX-Tests.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile GPX-Tests.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gpx-tests1.0.0 || $(MKDIR) .tmp/gpx-tests1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gpx-tests1.0.0/ && (cd `dirname .tmp/gpx-tests1.0.0` && $(TAR) gpx-tests1.0.0.tar gpx-tests1.0.0 && $(COMPRESS) gpx-tests1.0.0.tar) && $(MOVE) `dirname .tmp/gpx-tests1.0.0`/gpx-tests1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gpx-tests1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

earth.o: src/earth.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o earth.o src/earth.cpp

gpx-tests.o: src/gpx-tests.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpx-tests.o src/gpx-tests.cpp

geometry.o: src/geometry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geometry.o src/geometry.cpp

logs.o: src/logs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logs.o src/logs.cpp

position.o: src/position.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o position.o src/position.cpp

route.o: src/route.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route.o src/route.cpp

track.o: src/track.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o track.o src/track.cpp

xmlparser.o: src/xmlparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlparser.o src/xmlparser.cpp

xmlgenerator.o: src/xmlgenerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlgenerator.o src/xmlgenerator.cpp

gridworld.o: src/gridworld.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridworld.o src/gridworld.cpp

gridworld_route.o: src/gridworld_route.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridworld_route.o src/gridworld_route.cpp

gridworld_track.o: src/gridworld_track.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridworld_track.o src/gridworld_track.cpp

name.o: src/gpx-tests/name.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o name.o src/gpx-tests/name.cpp

numpositions.o: src/gpx-tests/numpositions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numpositions.o src/gpx-tests/numpositions.cpp

maxElevationN0774756.o: src/gpx-tests/maxElevationN0774756.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxElevationN0774756.o src/gpx-tests/maxElevationN0774756.cpp

accessOperator.o: src/gpx-tests/accessOperator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accessOperator.o src/gpx-tests/accessOperator.cpp

accessOperatorLogGenerator.o: src/gpx-tests/accessOperatorLogGenerator.cpp src/gpx-tests/accessOperatorLogGenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accessOperatorLogGenerator.o src/gpx-tests/accessOperatorLogGenerator.cpp

maxLongitudeN0743797.o: src/gpx-tests/maxLongitudeN0743797.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxLongitudeN0743797.o src/gpx-tests/maxLongitudeN0743797.cpp

steepestGradient.o: src/gpx-tests/steepestGradient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o steepestGradient.o src/gpx-tests/steepestGradient.cpp

steepestGradientN0742908.o: src/gpx-tests/steepestGradientN0742908.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o steepestGradientN0742908.o src/gpx-tests/steepestGradientN0742908.cpp

steepestGradient-N0826291.o: src/gpx-tests/steepestGradient-N0826291.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o steepestGradient-N0826291.o src/gpx-tests/steepestGradient-N0826291.cpp

findNameOf.o: src/gpx-tests/findNameOf.cpp src/gpx-tests/findNameOfGPXGenerator.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findNameOf.o src/gpx-tests/findNameOf.cpp

findPositionN0724629.o: src/gpx-tests/findPositionN0724629.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findPositionN0724629.o src/gpx-tests/findPositionN0724629.cpp

findpositionn0734208.o: src/gpx-tests/findpositionn0734208.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findpositionn0734208.o src/gpx-tests/findpositionn0734208.cpp

maxSpeedN0737110.o: src/gpx-tests/maxSpeedN0737110.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxSpeedN0737110.o src/gpx-tests/maxSpeedN0737110.cpp

maxlatitude.o: src/gpx-tests/maxlatitude.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxlatitude.o src/gpx-tests/maxlatitude.cpp

maxSpeedN0733894.o: src/gpx-tests/maxSpeedN0733894.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxSpeedN0733894.o src/gpx-tests/maxSpeedN0733894.cpp

N0774446-TotalHeightGain.o: src/gpx-tests/N0774446-TotalHeightGain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o N0774446-TotalHeightGain.o src/gpx-tests/N0774446-TotalHeightGain.cpp

maxGradient-n0756303.o: src/gpx-tests/maxGradient-n0756303.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxGradient-n0756303.o src/gpx-tests/maxGradient-n0756303.cpp

maxspeedn0736188.o: src/gpx-tests/maxspeedn0736188.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxspeedn0736188.o src/gpx-tests/maxspeedn0736188.cpp

totalLengthTest_n0755314.o: src/gpx-tests/totalLengthTest_n0755314.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o totalLengthTest_n0755314.o src/gpx-tests/totalLengthTest_n0755314.cpp

netLength-N0704050.o: src/gpx-tests/netLength-N0704050.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netLength-N0704050.o src/gpx-tests/netLength-N0704050.cpp

restingTimeN0736563.o: src/gpx-tests/restingTimeN0736563.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o restingTimeN0736563.o src/gpx-tests/restingTimeN0736563.cpp

netHeightGain-N0679817.o: src/gpx-tests/netHeightGain-N0679817.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netHeightGain-N0679817.o src/gpx-tests/netHeightGain-N0679817.cpp

netHeightGain-N0675532.o: src/gpx-tests/netHeightGain-N0675532.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netHeightGain-N0675532.o src/gpx-tests/netHeightGain-N0675532.cpp

maxGradient-N0740369.o: src/gpx-tests/maxGradient-N0740369.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxGradient-N0740369.o src/gpx-tests/maxGradient-N0740369.cpp

MaxElevation-N0749370.o: src/gpx-tests/MaxElevation-N0749370.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MaxElevation-N0749370.o src/gpx-tests/MaxElevation-N0749370.cpp

minLongitude.o: src/gpx-tests/minLongitude.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minLongitude.o src/gpx-tests/minLongitude.cpp

minlatitude-n0743587.o: src/gpx-tests/minlatitude-n0743587.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minlatitude-n0743587.o src/gpx-tests/minlatitude-n0743587.cpp

netLength-N0745509.o: src/gpx-tests/netLength-N0745509.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netLength-N0745509.o src/gpx-tests/netLength-N0745509.cpp

maxLongitude.o: src/gpx-tests/maxLongitude.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxLongitude.o src/gpx-tests/maxLongitude.cpp

timesVisited-n0763258.o: src/gpx-tests/timesVisited-n0763258.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesVisited-n0763258.o src/gpx-tests/timesVisited-n0763258.cpp

maxLongitudeN0732961.o: src/gpx-tests/maxLongitudeN0732961.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxLongitudeN0732961.o src/gpx-tests/maxLongitudeN0732961.cpp

netHeightGain-N0701387.o: src/gpx-tests/netHeightGain-N0701387.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netHeightGain-N0701387.o src/gpx-tests/netHeightGain-N0701387.cpp

totalHeightGainN0724106.o: src/gpx-tests/totalHeightGainN0724106.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o totalHeightGainN0724106.o src/gpx-tests/totalHeightGainN0724106.cpp

netLength-N0731739.o: src/gpx-tests/netLength-N0731739.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netLength-N0731739.o src/gpx-tests/netLength-N0731739.cpp

minLongitudeN0735026.o: src/gpx-tests/minLongitudeN0735026.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minLongitudeN0735026.o src/gpx-tests/minLongitudeN0735026.cpp

findnameofn0665742.o: src/gpx-tests/findnameofn0665742.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findnameofn0665742.o src/gpx-tests/findnameofn0665742.cpp

maxlatitude_N0745180.o: src/gpx-tests/maxlatitude_N0745180.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maxlatitude_N0745180.o src/gpx-tests/maxlatitude_N0745180.cpp

totalTime_N0751567.o: src/gpx-tests/totalTime_N0751567.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o totalTime_N0751567.o src/gpx-tests/totalTime_N0751567.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

